spring.application.name=rups-geography-backend

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000
spring.data.redis.repositories.enabled=true

server.port=8081

cors.allowed-origins=http://localhost:3000,http://localhost:3001
